package com.mhky.dianhuotong.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mhky.dianhuotong.database.SearchBaseInfo;

import com.mhky.dianhuotong.greendao.SearchBaseInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchBaseInfoDaoConfig;

    private final SearchBaseInfoDao searchBaseInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchBaseInfoDaoConfig = daoConfigMap.get(SearchBaseInfoDao.class).clone();
        searchBaseInfoDaoConfig.initIdentityScope(type);

        searchBaseInfoDao = new SearchBaseInfoDao(searchBaseInfoDaoConfig, this);

        registerDao(SearchBaseInfo.class, searchBaseInfoDao);
    }
    
    public void clear() {
        searchBaseInfoDaoConfig.clearIdentityScope();
    }

    public SearchBaseInfoDao getSearchBaseInfoDao() {
        return searchBaseInfoDao;
    }

}
